modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
# issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
    modId="fauna" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Fauna Mod" #mandatory
    # updateJSONURL="http://myurl.me/" #optional
    # displayURL="http://example.com/" #optional
    # logoFile="bamboo.png" #optional
    # credits="" #optional
    authors="Doc Bok" #optional
    description='''
    Adds a bunch of new animals to the Minecraft world.
    '''

    [[dependencies]] #optional
        modId="forge" #mandatory
        mandatory=true #mandatory
        versionRange="[37,)" #mandatory        ordering="NONE"
        side="BOTH"

    # Here's another dependency
    [[dependencies]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.17.1, 1.18]"
        ordering="NONE"
        side="BOTH"
